Adds placeholders
digitalocean/kubernetes-sample-apps pull request #28
Opened 2022-09-19 11:04 UTC by v-bpastiu

- adds placeholders for DOCR images and kube context for tilt

2022-09-19 12:12 UTC, v-ctiutiu requested changes

2022-09-19 12:12 UTC, v-ctiutiu commented on microservices-demo/Tiltfile-dev
> +allow_k8s_contexts('<YOUR_KUBERNETES_CONTEXT>')
I would say:

```
allow_k8s_contexts('<YOUR_KUBERNETES_CONTEXT_HERE>')
```

2022-09-19 12:12 UTC, v-ctiutiu commented on microservices-demo/kustomize/base/cartservice.yaml
> +        image: <YOUR_DOCR_IMAGE>
I don't think we need to replace everything with a placeholder, only the relevant part. Something like:

```
image: registry.digitalocean.com/<YOUR_DOCR_REPO_NAME_HERE>/cartservice:1.0.0
```

2022-09-19 12:12 UTC, v-ctiutiu commented on microservices-demo/kustomize/base/checkoutservice.yaml
> +          image: <YOUR_DOCR_IMAGE>
I don't think we need to replace everything with a placeholder, only the relevant part. Something like:

```
image: registry.digitalocean.com/<YOUR_DOCR_REPO_NAME_HERE>/checkoutservice:1.0.0
```

2022-09-19 12:12 UTC, v-ctiutiu commented on microservices-demo/kustomize/base/currencyservice.yaml
> +        image: <YOUR_DOCR_IMAGE>
I don't think we need to replace everything with a placeholder, only the relevant part. Something like:

```
image: registry.digitalocean.com/<YOUR_DOCR_REPO_NAME_HERE>/currencyservice:1.0.0
```

2022-09-19 12:12 UTC, v-ctiutiu commented on microservices-demo/kustomize/base/emailservice.yaml
> +        image: <YOUR_DOCR_IMAGE>
I don't think we need to replace everything with a placeholder, only the relevant part. Something like:

```
image: registry.digitalocean.com/<YOUR_DOCR_REPO_NAME_HERE>/emailservice:1.0.0
```

2022-09-19 12:12 UTC, v-ctiutiu commented on microservices-demo/kustomize/base/paymentservice.yaml
> +        image: <YOUR_DOCR_IMAGE>
I don't think we need to replace everything with a placeholder, only the relevant part. Something like:

```
image: registry.digitalocean.com/<YOUR_DOCR_REPO_NAME_HERE>/paymentservice:1.0.0
```

2022-09-19 12:12 UTC, v-ctiutiu commented on microservices-demo/kustomize/base/productcatalogservice.yaml
> +        image: <YOUR_DOCR_IMAGE>
I don't think we need to replace everything with a placeholder, only the relevant part. Something like:

```
image: registry.digitalocean.com/<YOUR_DOCR_REPO_NAME_HERE>/productcatalogservice:1.0.0
```

2022-09-19 12:12 UTC, v-ctiutiu commented on microservices-demo/kustomize/base/recommendationservice.yaml
> +        image: <YOUR_DOCR_IMAGE>
I don't think we need to replace everything with a placeholder, only the relevant part. Something like:

```
image: registry.digitalocean.com/<YOUR_DOCR_REPO_NAME_HERE>/recommendationservice:1.0.0
```

2022-09-19 12:12 UTC, v-ctiutiu commented on microservices-demo/kustomize/base/shippingservice.yaml
> +        image: <YOUR_DOCR_IMAGE>
I don't think we need to replace everything with a placeholder, only the relevant part. Something like:

```
image: registry.digitalocean.com/<YOUR_DOCR_REPO_NAME_HERE>/shippingservice:1.0.0
```

2022-09-19 14:28 UTC, v-ctiutiu approved these changes
Looks good to me now.

2022-09-20 02:53 UTC, bikram20 approved these changes

2022-09-20 02:53 UTC, merged